// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SONTRA_API.Data;

#nullable disable

namespace SONTRA_API.Migrations
{
    [DbContext(typeof(SonTraDbContext))]
    [Migration("20260606163944_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SONTRA_API.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SpecificAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SONTRA_API.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("ContentEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentVI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TitleVI")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("SONTRA_API.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscountVND")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinOrderVND")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SONTRAFREE",
                            DiscountValue = 20000m,
                            EndDate = new DateTime(2027, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsPercentage = false,
                            MinOrderVND = 100000m,
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UsageLimit = 1000,
                            UsedCount = 0
                        });
                });

            modelBuilder.Entity("SONTRA_API.Models.CustomerProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("MembershipTier")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("UserId");

                    b.ToTable("CustomerProfiles");
                });

            modelBuilder.Entity("SONTRA_API.Models.GiftBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BoxSize")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CardMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailId")
                        .IsUnique();

                    b.ToTable("GiftBoxes");
                });

            modelBuilder.Entity("SONTRA_API.Models.GiftBoxItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GiftBoxId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiftBoxId");

                    b.HasIndex("ProductId");

                    b.ToTable("GiftBoxItems");
                });

            modelBuilder.Entity("SONTRA_API.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginProvince")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hoa cúc sấy giòn tự nhiên.",
                            DescriptionEN = "Crispy dried natural chamomile flowers.",
                            Latitude = 20.6464m,
                            Longitude = 106.0511m,
                            Name = "Hoa cúc",
                            NameEN = "Chrysanthemum",
                            OriginProvince = "Hưng Yên"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hạt kỷ tử chín mọng phơi khô.",
                            DescriptionEN = "Ripe dried goji berries.",
                            Latitude = 11.5684m,
                            Longitude = 108.9904m,
                            Name = "Kỷ tử",
                            NameEN = "Goji Berry",
                            OriginProvince = "Ninh Thuận"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bí đao sấy khô giải nhiệt.",
                            DescriptionEN = "Dried winter melon slices.",
                            Latitude = 10.9574m,
                            Longitude = 106.8427m,
                            Name = "Bí đao",
                            NameEN = "Winter Melon",
                            OriginProvince = "Đồng Nai"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lá dứa thơm sấy lạnh.",
                            DescriptionEN = "Aromatic cold-dried pandan leaves.",
                            Latitude = 11.9404m,
                            Longitude = 108.4583m,
                            Name = "Lá dứa",
                            NameEN = "Pandan Leaf",
                            OriginProvince = "Lâm Đồng"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Táo đỏ cắt lát giàu dinh dưỡng.",
                            DescriptionEN = "Sliced nutrient-rich red jujube dates.",
                            Latitude = 20.2506m,
                            Longitude = 105.9744m,
                            Name = "Táo đỏ",
                            NameEN = "Red Date",
                            OriginProvince = "Ninh Bình"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Cây lạc tiên hoang dã hái ở bán đảo Sơn Trà.",
                            DescriptionEN = "Wild passionflower vine harvested from Son Tra peninsula.",
                            Latitude = 16.1211m,
                            Longitude = 108.2783m,
                            Name = "Lạc tiên",
                            NameEN = "Passion Flower",
                            OriginProvince = "Đà Nẵng"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Tâm sen khô đắng nhẹ an thần.",
                            DescriptionEN = "Lotus seed core/plumule, naturally calming.",
                            Latitude = 10.4542m,
                            Longitude = 105.6322m,
                            Name = "Tâm sen",
                            NameEN = "Lotus Plumule",
                            OriginProvince = "Đồng Tháp"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Lá dâu tằm non sấy ráo.",
                            DescriptionEN = "Young mulberry leaves, dried gently.",
                            Latitude = 21.2731m,
                            Longitude = 106.1946m,
                            Name = "Lá dâu tằm",
                            NameEN = "Mulberry Leaf",
                            OriginProvince = "Bắc Giang"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Hoa Atiso đỏ sấy chua thanh.",
                            DescriptionEN = "Tangy dried hibiscus/red artichoke flowers.",
                            Latitude = 11.9404m,
                            Longitude = 108.4583m,
                            Name = "Atiso",
                            NameEN = "Artichoke",
                            OriginProvince = "Lâm Đồng"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Rễ cam thảo xắt mỏng ngọt hậu.",
                            DescriptionEN = "Sweet sliced licorice root.",
                            Latitude = 15.5872m,
                            Longitude = 107.9794m,
                            Name = "Cam thảo",
                            NameEN = "Licorice Root",
                            OriginProvince = "Quảng Nam"
                        });
                });

            modelBuilder.Entity("SONTRA_API.Models.LoyaltyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PointsChanged")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("LoyaltyTransactions");
                });

            modelBuilder.Entity("SONTRA_API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GuestPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ShippingFeeUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShippingFeeVND")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingTrackingCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalAmountUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmountVND")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SONTRA_API.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPriceUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPriceVND")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("SONTRA_API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGiftBoxShell")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PriceUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceVND")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giúp thư giãn tinh thần, làm dịu lo âu và mang lại giấc ngủ dịu êm.",
                            DescriptionEN = "Relaxes the mind, calms anxiety, and brings a gentle sleep.",
                            ImageURL = "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?q=80&w=600&auto=format&fit=crop",
                            IsActive = true,
                            IsGiftBoxShell = false,
                            Name = "Trà Êm (Hoa cúc, Kỷ tử)",
                            NameEN = "Em Tea (Chrysanthemum, Wolfberry)",
                            PriceUSD = 3.00m,
                            PriceVND = 75000m,
                            Slug = "tra-em-hoa-cuc-ky-tu",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giúp thanh nhiệt, giải độc gan, làm mát cơ thể cho ngày dài năng động.",
                            DescriptionEN = "Cools the liver, detoxifies, and refreshes the body for active days.",
                            ImageURL = "https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=600&auto=format&fit=crop",
                            IsActive = true,
                            IsGiftBoxShell = false,
                            Name = "Trà Thanh (Bí đao, Hoa cúc, Táo đỏ...)",
                            NameEN = "Thanh Tea (Winter melon, Chrysanthemum...)",
                            PriceUSD = 3.40m,
                            PriceVND = 85000m,
                            Slug = "tra-thanh-mat-gan-giai-nhiet",
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trị mất ngủ kinh niên, giảm căng thẳng thần kinh, mang lại giấc ngủ sâu an lành.",
                            DescriptionEN = "Combats chronic insomnia, reduces nerve stress, and provides a deep peaceful sleep.",
                            ImageURL = "https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop",
                            IsActive = true,
                            IsGiftBoxShell = false,
                            Name = "Trà Yên (Lạc tiên, Tâm sen, Lá dâu tằm)",
                            NameEN = "Yen Tea (Passionflower, Lotus seed core...)",
                            PriceUSD = 3.60m,
                            PriceVND = 90000m,
                            Slug = "tra-yen-ngu-ngon-sau-giac",
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vị ngọt thanh từ cam thảo kết hợp Atiso giúp lọc gan, dịu nhẹ đường ruột.",
                            DescriptionEN = "Mild sweet licorice combined with artichoke to purify liver and soothe digestive tract.",
                            ImageURL = "https://images.unsplash.com/photo-1563822249548-9a72b6353cd1?q=80&w=600&auto=format&fit=crop",
                            IsActive = true,
                            IsGiftBoxShell = false,
                            Name = "Trà Dịu (Atiso, Cam thảo)",
                            NameEN = "Diu Tea (Artichoke, Licorice)",
                            PriceUSD = 3.20m,
                            PriceVND = 80000m,
                            Slug = "tra-diu-ngot-hau-thanh-loc",
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vỏ hộp quà rỗng kèm thiệp chúc mừng tự viết để bạn tùy chọn vị trà.",
                            DescriptionEN = "Empty gift box case with custom card for personalized selections.",
                            ImageURL = "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=600&auto=format&fit=crop",
                            IsActive = true,
                            IsGiftBoxShell = true,
                            Name = "Vỏ Hộp Quà Tự Thiết Kế",
                            NameEN = "Custom Gift Box Case",
                            PriceUSD = 1.20m,
                            PriceVND = 30000m,
                            Slug = "vo-hop-qua-tu-thiet-ke",
                            StockQuantity = 1000
                        });
                });

            modelBuilder.Entity("SONTRA_API.Models.ProductIngredient", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ProductIngredients");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IngredientId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 3
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 4
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 5
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 6
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 7
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 8
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 9
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 10
                        });
                });

            modelBuilder.Entity("SONTRA_API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuestName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SONTRA_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@sontra.com",
                            FullName = "Chủ cửa hàng (Admin)",
                            IsActive = true,
                            PasswordHash = "240eb0f5a83cd773f32467d3e098867a57a149c90eb21cf8b73fdfb55ec7f7c4",
                            PhoneNumber = "0900000001",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "warehouse@sontra.com",
                            FullName = "Nhân viên kho (Warehouse)",
                            IsActive = true,
                            PasswordHash = "cb6cd7efc12ff357d622f6723226db2c78119eb46146ff9d8aa124ff39665bc7",
                            PhoneNumber = "0900000002",
                            Role = "Warehouse"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@sontra.com",
                            FullName = "Nhân viên duyệt đơn (Staff)",
                            IsActive = true,
                            PasswordHash = "cb6cd7efc12ff357d622f6723226db2c78119eb46146ff9d8aa124ff39665bc7",
                            PhoneNumber = "0900000003",
                            Role = "Staff"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "marketing@sontra.com",
                            FullName = "Nhân viên truyền thông (Content)",
                            IsActive = true,
                            PasswordHash = "2f53d4ebc335a122e23d1ff394df3c5000570bcf4769cf373dfa10526e85746b",
                            PhoneNumber = "0900000004",
                            Role = "Content"
                        });
                });

            modelBuilder.Entity("SONTRA_API.Models.Address", b =>
                {
                    b.HasOne("SONTRA_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SONTRA_API.Models.Blog", b =>
                {
                    b.HasOne("SONTRA_API.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("SONTRA_API.Models.CustomerProfile", b =>
                {
                    b.HasOne("SONTRA_API.Models.User", "User")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("SONTRA_API.Models.CustomerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SONTRA_API.Models.GiftBox", b =>
                {
                    b.HasOne("SONTRA_API.Models.OrderDetail", "OrderDetail")
                        .WithOne("GiftBox")
                        .HasForeignKey("SONTRA_API.Models.GiftBox", "OrderDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("SONTRA_API.Models.GiftBoxItem", b =>
                {
                    b.HasOne("SONTRA_API.Models.GiftBox", "GiftBox")
                        .WithMany("GiftBoxItems")
                        .HasForeignKey("GiftBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SONTRA_API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiftBox");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SONTRA_API.Models.LoyaltyTransaction", b =>
                {
                    b.HasOne("SONTRA_API.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SONTRA_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SONTRA_API.Models.Order", b =>
                {
                    b.HasOne("SONTRA_API.Models.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId");

                    b.HasOne("SONTRA_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Coupon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SONTRA_API.Models.OrderDetail", b =>
                {
                    b.HasOne("SONTRA_API.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SONTRA_API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SONTRA_API.Models.ProductIngredient", b =>
                {
                    b.HasOne("SONTRA_API.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SONTRA_API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SONTRA_API.Models.Review", b =>
                {
                    b.HasOne("SONTRA_API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SONTRA_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SONTRA_API.Models.GiftBox", b =>
                {
                    b.Navigation("GiftBoxItems");
                });

            modelBuilder.Entity("SONTRA_API.Models.OrderDetail", b =>
                {
                    b.Navigation("GiftBox");
                });

            modelBuilder.Entity("SONTRA_API.Models.User", b =>
                {
                    b.Navigation("CustomerProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
